export const initialContent = {
  0: {
    id: 0,
    name: "Personal Details",
    isShow: true,
    fullName: "",
    job: "",
    email: "",
    phone: "",
    address: "",
  },
  1: {
    id: 1,
    name: "About Me",
    isShow: false,
    description: "",
  },
  2: {
    id: 2,
    name: "Professional Experience",
    isShow: false,
    list: [
      {
        id: 0,
        name: "New",
        city: "",
        country: "",
        start: "",
        end: "",
        description: "",
      },
    ],
  },
  3: {
    id: 3,
    name: "Education",
    isShow: false,
    list: [
      {
        id: 0,
        name: "New",
        school: "",
        schoolLink: "",
        city: "",
        country: "",
        start: "",
        end: "",
        description: "",
      },
    ],
  },
  4: {
    id: 4,
    name: "Skills",
    isShow: false,
    list: [{ id: 0, name: "New" }],
  },
  5: {
    id: 5,
    name: "Projects",
    isShow: false,
    list: [
      {
        id: 0,
        name: "New",
        projectLink: "",
        start: "",
        end: "",
        description: "",
        link: "",
      },
    ],
  },
  6: {
    id: 6,
    name: "Languages",
    isShow: false,
    list: [{ id: 0, name: "New" }],
  },
};
